config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'registrations'
  }


  resources :events do
    collection do
      get 'search'
    end
 
    resources :events
    resources :ticket_types, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:create, :destroy]
   end
 

  require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'


  get 'booking_history', to: 'bookings#history', as: 'booking_history'
  delete 'booking_history/:id', to: 'bookings#cancel', as: 'cancel_booking'

  root 'home#index'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :ticket_type

  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: :history

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @ticket_type = TicketType.find(params[:booking][:ticket_type_id])
    @quantity = params[:booking][:quantity].to_i

    if @quantity > 0 && @quantity <= @ticket_type.available_quantity
      Booking.transaction do
        @ticket_type.available_quantity -= @quantity
        @ticket_type.save!
        @booking.save!
        update_booking_cache(current_user)
                         
      end
       


      TicketConfirmationJob.perform_later(current_user, @booking)

      redirect_to @booking.event, notice: 'Booking was successfully created.'
    else
      redirect_to @booking.event, alert: 'Unable to create booking. Invalid quantity.'
    end
  end

  def history
    x = Rails.cache.fetch("user_#{current_user.email}_bookings")
    puts('vvvvvvvv',x.to_yaml)
    @bookings = Rails.cache.fetch("user_#{current_user.email}_bookings") do current_user.bookings.includes(:event, :ticket_type).order(created_at: :desc) end
  end

  def cancel
    @booking = current_user.bookings.find(params[:id])
    @ticket_type = @booking.ticket_type

    Booking.transaction do
      @ticket_type.available_quantity += @booking.quantity
      @ticket_type.save!
      @booking.destroy!
      update_booking_cache(current_user)
    end
    redirect_to booking_history_path, alert: 'Booking was successfully canceled.'
  end

  def update_booking_cache(user)
    bookings = user.bookings.includes(:event, :ticket_type).order(created_at: :desc)
    Rails.cache.write("user_#{current_user.email}_bookings", bookings)
  end

  private

  def booking_params
    params.require(:booking).permit(:event_id, :ticket_type_id, :quantity)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/history.html.erb
<h2>Your Booking History</h2>

<% if @bookings.any? %>
  <table>
    <thead>
      <tr>
        <th>Event</th>
        <th>Ticket Type</th>
        <th>Quantity</th>
        <th>Total Cost</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.event.name %></td>
          <td><%= booking.ticket_type.name %></td>
          <td><%= booking.quantity %></td>
          <td><%= number_to_currency(booking.ticket_type.price * booking.quantity) %></td>
          <td>
            <%= button_to 'Cancel Booking', cancel_booking_path(booking), method: :delete,  form: {data: {'turbo_confirm': 'Are you sure?'}}  %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You have no bookings.</p>
<% end %>

app/views/bookings/ticket_details.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Ticket Details</title>
    <style>
      body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; }
      .container { margin: 20px; }
      .header { text-align: center; }
      .details { margin-top: 20px; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>Ticket Details</h1>
      </div>
      <div class="details">
        <p><strong>Event:</strong> <%= booking.event.name %></p>
        <p><strong>Date:</strong> <%= booking.event.date %></p>
         <p><strong>City:</strong> <%= booking.event.city %></p>
        <p><strong>Ticket Type:</strong> <%= booking.ticket_type.name %></p>
        <p><strong>Quantity:</strong> <%= booking.quantity %></p>
          
      </div>
    </div>
  </body>
</html>