config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'registrations'
  }


  resources :events do
    collection do
      get 'search'
    end
 
    resources :events
    resources :ticket_types, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:create, :destroy]
   end
 

  require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'


  get 'booking_history', to: 'bookings#history', as: 'booking_history'
  delete 'booking_history/:id', to: 'bookings#cancel', as: 'cancel_booking'

  root 'home#index'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :ticket_types,dependent: :destroy
  has_many :bookings,dependent: :destroy
  
  has_many :users, through: :bookings
  has_one_attached :image
  validates :name, :description, :date, :city, :producer, :artists, presence: true
  validate :date_cannot_be_in_the_past

  private

  def date_cannot_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end

 include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name "events_#{Rails.env}"

 # Define the Elasticsearch index mappings
  settings index: { number_of_shards: 1 } do
    mappings dynamic: false do
      indexes :name, type: :text, analyzer: 'english'
      indexes :artists, type: :text, analyzer: 'english'
      indexes :producer, type: :text, analyzer: 'english'
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: %w[name artists producer]
          }
        }
      }
    )
  end

    def as_indexed_json(options = {})
    self.as_json(
      only: [:name, :artists, :producer]
    )
  end

  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
   before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    if params[:query].present?
      @events = Event.where("name LIKE ? OR artists LIKE ? OR producer LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%","%#{params[:query]}%")
    else
      @events = Event.all
    end
  end

  #  def index
  #   if params[:query].present?
  #     @events = Event.search(params[:query]).records
  #   else
  #     @events = Event.all
  #   end
  # end

  # Other actions remain unchanged...

 
  def set_event
    @event = Event.find(params[:id])
  end

  

  def show
    @event = Event.find(params[:id])
    
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end



  def require_admin
    unless current_user&.admin?
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to home_index_path, notice: 'Event was successfully deleted.'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :city, :producer, :artists, :image)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_list.html.erb
<% if @events.any? %>
  <ul>
    <% @events.each do |event| %>
      <li>
        <h2><%= link_to event.name, event_path(event) %></h2>
        <p><%= event.description %></p>
        <p><%= event.artists %></p>
        <p><%= event.date.strftime("%B %d, %Y") %></p>
        <p><%= event.city %></p>
        <p><%= event.producer %></p>
        <% if event.image.attached? %>
          <%= image_tag event.image, style: "max-width: 200px;" %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No events found</p>
<% end %>

app/views/events/index.html.erb
<h2>Events</h2>



<%= form_with url: events_path, method: :get, local: true, id: 'search_form' do %>
  <div class="field">
    <%= label_tag :query, "Search Events" %>
    <%= text_field_tag :query, params[:query], id: 'search_box' %>
  </div>
<% end %>

<div id="search_results">
  <%= render partial: 'events_list' %>
</div>

<div class='button-6'>

<% if can? :create, Event %>
  <%= link_to 'New Event', new_event_path %>
<% end %>
</div>

app/views/events/new.html.erb
<section class="vh-100 ">

  <div class="container py-5 h-100">
     
    <div class="row d-flex justify-content-center align-items-top h-100">
      <div class="col-12 col-md-12 col-lg-8 col-xl-6">
        <div class="card gradient-custom  text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <div class='mt-5 mb-5'>
<h2>Create New Event</h2>
</div>

<%= form_with model: @event, local: true do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-tt-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="input-tt-field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="input-tt-field">
    <%= form.label :date %>
    <div class='input-tt-select'>
    <%= form.datetime_select :date %>
  </div>
  </div>

  <div class="input-tt-field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="input-tt-field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="input-tt-field">
    <%= form.label :artists %>
    <%= form.text_area :artists %>
  </div>

  <div class="input-tt-field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

app/views/events/show.html.erb
<div class='container event-details-page'>
  <div class='event-dpage-left'>
   
    
    <div class='event-dpage-box event-dpage-item event-item'>
<h2><%= @event.name.capitalize %></h2>
<div class='img-box'>

<% if @event.image.attached? %>
  <%= image_tag @event.image %>
<% else %>
<%= image_tag(root_url + "default2.jpg", :alt => "event") %>
<% end %>
</div>
<div class='event-dpage-details'>
  <div class='mt-2 mb-0 pb-0'
<>About :</span>
</div>
<div class='ml-3 pl-3'>
<div class='mt-1 pt-0 pb-3'><%= @event.description %></div>
</div>
<p>Date: <strong> <%= @event.date.strftime("%B %d, %Y") %></p></strong>
<p>City: <strong> <%= @event.city %></p></strong>
<p>Producer: <strong> <%= @event.producer %></p></strong>
<p>Artists: <strong> <%= @event.artists %></p></strong> 

</div>
<% if can? :delete, @event %>
<div class="mb-3 mt-3 d-flex justify-content-center">

  <%= button_to 'Delete Event', event_path(@event), {class:'delete-event-button', method: :delete, confirm: 'are u sure?'} %>

<% end %>
</div>
</div>
</div>
 <div class='event-dpage-right'>

<div class='event-dpage-tkt-box event-dpage-item'>
<h3>Ticket Types</h3>
<table>
        
<% @event.ticket_types.each do |ticket_type| %>

  
    <tr>
   
      
  <td> <div class='col'> <p><strong><%= ticket_type.name %></strong>: $<%= ticket_type.price %></p></div> </td> 
   <td> <div class='col'>  <p>Total : <%= ticket_type.total_quantity %></p></div> </td> 
 <td>  <div class='col'>  <p>Available : <%= ticket_type.available_quantity %></p></div></td>
    <% if can? :destroy, ticket_type %>
  <td> <div class='col'>  
      <%= button_to 'Delete', event_ticket_type_path(@event, ticket_type), {class:'default-delete-button', method: :delete, confirm: 'are u sure?'} %>
   </div> </td>
  </tr>

  
    <% end %>
   
 


<% end %>
   </table>
<% if can? :create, TicketType %>
<% if @event.date >= Date.today %>
<div class='button-6'>


  <%= link_to 'Add Ticket Type', new_event_ticket_type_path(@event) %>
  <% else %>
  <button type="button"class="btn button-6" disabled>Add Ticket Type</button>
  <% end %>
</div>
<% end %>


<% if can? :create, Booking %>
<div class='event-dpage-booking-box event-dpage-item'>

<h3>Book Tickets</h3>
  <%= form_with class:"ticket-type-form" , model: [@event, Booking.new], local: true do |form| %>
    <div class="field">
      <%= form.label :ticket_type_id, 'Select Ticket Type' %>
      <%= form.collection_select :ticket_type_id, @event.ticket_types, :id, :name,class:"form-select form-select-lg"  %>
    </div>
    <div class="field">
      <%= form.label :quantity, 'Number of Tickets' %>
      <%= form.number_field :quantity, min: 1 %>
    </div>
    <%= form.hidden_field :event_id, value: @event.id %>
    <% if @event.ticket_types %>
    <div class="actions" >
      <% if @event.date >= Date.today %>
      <%= form.submit 'Book Ticket' , class: 'button-6' %>
       <% else %>
       <button type="button" class=" btn button-6" disabled>Book Ticket</button>
       <% end %>
    
    </div>
   <% end %>
   <% end %>
<% end %>
</div>
</div>
</div>